"""cache upgrade

Revision ID: 0f4acffcc18b
Revises: 4ef19d589a05
Create Date: 2020-08-24 07:19:44.724576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f4acffcc18b'
down_revision = '4ef19d589a05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yt_video', sa.Column('found', sa.Boolean(), nullable=True))
    op.add_column('yt_video', sa.Column('found_at', sa.DateTime(), nullable=True))
    op.add_column('yt_video', sa.Column('pickle', sa.PickleType(), nullable=True))
    op.drop_column('yt_video', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yt_video', sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('yt_video', 'pickle')
    op.drop_column('yt_video', 'found_at')
    op.drop_column('yt_video', 'found')
    # ### end Alembic commands ###
