"""fish

Revision ID: 4733d7261b6f
Revises: 407dd5ded242
Create Date: 2020-10-22 21:23:58.376588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4733d7261b6f'
down_revision = '407dd5ded242'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('result_cache',
    sa.Column('id', sa.String(length=240), nullable=False),
    sa.Column('pickle', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('result_cache')
    # ### end Alembic commands ###
