"""drop uneeded

Revision ID: 65d2d7cb2d38
Revises: 76ddade3ec0d
Create Date: 2020-08-25 04:44:14.476851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65d2d7cb2d38'
down_revision = '76ddade3ec0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('yt_video', 'found')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yt_video', sa.Column('found', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
