"""init

Revision ID: 76ddade3ec0d
Revises: 
Create Date: 2020-08-25 03:14:08.032260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76ddade3ec0d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yt_video',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('found', sa.Boolean(), nullable=True),
    sa.Column('found_at', sa.DateTime(), nullable=True),
    sa.Column('pickle', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('yt_video')
    # ### end Alembic commands ###
