"""fish

Revision ID: 8ba5678b7708
Revises: 4733d7261b6f
Create Date: 2020-10-22 21:28:31.568920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ba5678b7708'
down_revision = '4733d7261b6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result_cache', sa.Column('cache_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('result_cache', 'cache_time')
    # ### end Alembic commands ###
